name = "test-api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
route = { pattern = "api.test.dev", custom_domain = true }

[observability.logs]
enabled = true
